version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./bin/rails s -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'
    volumes:
      - .:/web
      - gem-store:/usr/local/bundle:cached
      - node_modules:/web/node_modules
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
volumes:
  db-data:
  gem-store:
  node_modules: